#include "snapstore.h"
#include "snapmon_ioctl.h"
#include <errno.h>
#include <fcntl.h>
#include <inttypes.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

typedef struct { snapshot_header_t h; uint64_t *map; } snapshot_t;
typedef struct { meta_header_t h; uint64_t *current; snapshot_t *snaps; } metadata_t;

static void die(const char *m){ perror(m); exit(EXIT_FAILURE); }
static void fail(const char *m){ fprintf(stderr,"error: %s\n",m); exit(EXIT_FAILURE); }
static void path_join(char *out,size_t n,const char *dir,const char *file){ if(snprintf(out,n,"%s/%s",dir,file)>=(int)n) fail("path too long"); }
static void write_all(int fd,const void *buf,size_t n){ const char *p=buf; while(n){ ssize_t k=write(fd,p,n); if(k<0){if(errno==EINTR)continue;die("write");} p+=k;n-=(size_t)k;} }
static void read_all(int fd,void *buf,size_t n){ char *p=buf; while(n){ ssize_t k=read(fd,p,n); if(k<0){if(errno==EINTR)continue;die("read");} if(k==0)fail("unexpected end of metadata");p+=k;n-=(size_t)k;} }
static void pread_all(int fd,void *buf,size_t n,off_t off){ char *p=buf; while(n){ ssize_t k=pread(fd,p,n,off);if(k<0){if(errno==EINTR)continue;die("pread");}if(k==0)fail("unexpected end of block store");p+=k;n-=(size_t)k;off+=k;} }
static void free_meta(metadata_t *m){ if(!m)return; for(uint32_t i=0;i<m->h.snapshot_count;i++)free(m->snaps[i].map);free(m->snaps);free(m->current);memset(m,0,sizeof(*m)); }
static void load_meta(const char *dir,metadata_t *m){ char path[PATH_MAX];path_join(path,sizeof(path),dir,"metadata.bin");int fd=open(path,O_RDONLY);if(fd<0)die("open metadata");memset(m,0,sizeof(*m));read_all(fd,&m->h,sizeof(m->h));if(m->h.magic!=SNAPSTORE_MAGIC||m->h.version!=SNAPSTORE_VERSION||m->h.block_size!=SNAPSTORE_BLOCK_SIZE)fail("invalid store format");if(!m->h.logical_blocks||m->h.snapshot_count>SNAPSTORE_MAX_SNAPSHOTS)fail("corrupt metadata");size_t z=(size_t)m->h.logical_blocks*sizeof(uint64_t);m->current=malloc(z);if(!m->current)die("malloc");read_all(fd,m->current,z);m->snaps=calloc(m->h.snapshot_count,sizeof(snapshot_t));if(m->h.snapshot_count&&!m->snaps)die("calloc");for(uint32_t i=0;i<m->h.snapshot_count;i++){read_all(fd,&m->snaps[i].h,sizeof(snapshot_header_t));m->snaps[i].map=malloc(z);if(!m->snaps[i].map)die("malloc");read_all(fd,m->snaps[i].map,z);}char extra;if(read(fd,&extra,1)!=0)fail("metadata has trailing bytes");close(fd);}
static void fsync_dir(const char *dir){int fd=open(dir,O_RDONLY|O_DIRECTORY);if(fd>=0){fsync(fd);close(fd);}}
static void save_meta(const char *dir,metadata_t *m){char path[PATH_MAX],tmp[PATH_MAX];path_join(path,sizeof(path),dir,"metadata.bin");path_join(tmp,sizeof(tmp),dir,"metadata.tmp");int fd=open(tmp,O_WRONLY|O_CREAT|O_TRUNC,0600);if(fd<0)die("open metadata.tmp");write_all(fd,&m->h,sizeof(m->h));size_t z=(size_t)m->h.logical_blocks*sizeof(uint64_t);write_all(fd,m->current,z);for(uint32_t i=0;i<m->h.snapshot_count;i++){write_all(fd,&m->snaps[i].h,sizeof(snapshot_header_t));write_all(fd,m->snaps[i].map,z);}if(fsync(fd)<0)die("fsync metadata");if(close(fd)<0)die("close metadata");if(rename(tmp,path)<0)die("rename metadata");fsync_dir(dir);}
static void notify_driver(int event){int fd=open("/dev/snapmon",O_RDWR);if(fd>=0){(void)ioctl(fd,SNAPMON_IOC_EVENT,&event);close(fd);}}
static void cmd_init(const char *dir,const char *nstr){char *e;unsigned long n=strtoul(nstr,&e,10);if(*e||!n||n>1000000)fail("logical blocks must be 1..1000000");if(mkdir(dir,0700)<0&&errno!=EEXIST)die("mkdir");char data[PATH_MAX],meta[PATH_MAX];path_join(data,sizeof(data),dir,"blocks.dat");path_join(meta,sizeof(meta),dir,"metadata.bin");if(access(meta,F_OK)==0)fail("store already exists");int fd=open(data,O_CREAT|O_EXCL|O_WRONLY,0600);if(fd<0)die("create blocks.dat");if(fsync(fd)<0)die("fsync blocks.dat");close(fd);metadata_t m={0};m.h=(meta_header_t){SNAPSTORE_MAGIC,SNAPSTORE_VERSION,SNAPSTORE_BLOCK_SIZE,(uint32_t)n,0,0,1};m.current=malloc(n*sizeof(uint64_t));if(!m.current)die("malloc");for(unsigned long i=0;i<n;i++)m.current[i]=SNAPSTORE_UNMAPPED;save_meta(dir,&m);free_meta(&m);printf("Initialized %s: %lu logical blocks, %u-byte blocks\n",dir,n,SNAPSTORE_BLOCK_SIZE);}
static int find_snapshot(metadata_t *m,const char *name){for(uint32_t i=0;i<m->h.snapshot_count;i++)if(strcmp(m->snaps[i].h.name,name)==0)return (int)i;return -1;}
static void validate_name(const char *n){size_t z=strlen(n);if(!z||z>=SNAPSTORE_NAME_MAX)fail("snapshot name must be 1..63 characters");for(size_t i=0;i<z;i++)if(n[i]=='/'||n[i]=='\\')fail("snapshot name cannot contain slashes");}
static void cmd_write(const char *dir,const char *bstr,const char *input){metadata_t m;load_meta(dir,&m);char *e;unsigned long b=strtoul(bstr,&e,10);if(*e||b>=m.h.logical_blocks)fail("block index out of range");int in=open(input,O_RDONLY);if(in<0)die("open input");unsigned char buf[SNAPSTORE_BLOCK_SIZE];ssize_t k=read(in,buf,sizeof(buf));if(k<0)die("read input");char extra;if(read(in,&extra,1)>0)fail("input exceeds 4096 bytes");close(in);char data[PATH_MAX];path_join(data,sizeof(data),dir,"blocks.dat");int fd=open(data,O_WRONLY|O_APPEND);if(fd<0)die("open blocks.dat");off_t off=lseek(fd,0,SEEK_END);if(off<0)die("lseek");record_header_t h={SNAPSTORE_RECORD_MAGIC,(uint32_t)b,(uint32_t)k,snap_crc32(buf,(size_t)k)};write_all(fd,&h,sizeof(h));write_all(fd,buf,(size_t)k);if(fsync(fd)<0)die("fsync blocks.dat");close(fd);m.current[b]=(uint64_t)off;m.h.generation++;save_meta(dir,&m);free_meta(&m);notify_driver(SNAPMON_WRITE);printf("Wrote %zd bytes to logical block %lu\n",k,b);}
static int read_record(const char *dir,uint64_t off,uint32_t expected,unsigned char *buf,record_header_t *h){char path[PATH_MAX];path_join(path,sizeof(path),dir,"blocks.dat");int fd=open(path,O_RDONLY);if(fd<0)die("open blocks.dat");pread_all(fd,h,sizeof(*h),(off_t)off);if(h->magic!=SNAPSTORE_RECORD_MAGIC||h->logical_block!=expected||h->data_len>SNAPSTORE_BLOCK_SIZE){close(fd);return -1;}pread_all(fd,buf,h->data_len,(off_t)off+(off_t)sizeof(*h));close(fd);return snap_crc32(buf,h->data_len)==h->crc32?0:-1;}
static void cmd_read(const char *dir,const char *bstr,const char *output){metadata_t m;load_meta(dir,&m);char *e;unsigned long b=strtoul(bstr,&e,10);if(*e||b>=m.h.logical_blocks)fail("block index out of range");if(m.current[b]==SNAPSTORE_UNMAPPED)fail("block is unmapped");unsigned char buf[SNAPSTORE_BLOCK_SIZE];record_header_t h;if(read_record(dir,m.current[b],(uint32_t)b,buf,&h)<0)fail("record checksum or header verification failed");int fd=open(output,O_WRONLY|O_CREAT|O_TRUNC,0600);if(fd<0)die("open output");write_all(fd,buf,h.data_len);close(fd);free_meta(&m);printf("Read %u bytes from logical block %lu\n",h.data_len,b);}
static void cmd_snapshot(const char *dir,const char *name){validate_name(name);metadata_t m;load_meta(dir,&m);if(m.h.snapshot_count>=SNAPSTORE_MAX_SNAPSHOTS)fail("snapshot limit reached");if(find_snapshot(&m,name)>=0)fail("snapshot already exists");snapshot_t *s=realloc(m.snaps,(m.h.snapshot_count+1)*sizeof(snapshot_t));if(!s)die("realloc");m.snaps=s;snapshot_t *x=&m.snaps[m.h.snapshot_count];memset(x,0,sizeof(*x));strncpy(x->h.name,name,SNAPSTORE_NAME_MAX-1);x->h.created_at=(int64_t)time(NULL);size_t z=(size_t)m.h.logical_blocks*sizeof(uint64_t);x->map=malloc(z);if(!x->map)die("malloc");memcpy(x->map,m.current,z);m.h.snapshot_count++;m.h.generation++;save_meta(dir,&m);free_meta(&m);notify_driver(SNAPMON_SNAPSHOT);printf("Created snapshot '%s'\n",name);}
static void cmd_list(const char *dir){metadata_t m;load_meta(dir,&m);printf("Snapshots (%u):\n",m.h.snapshot_count);for(uint32_t i=0;i<m.h.snapshot_count;i++){char t[32];time_t v=(time_t)m.snaps[i].h.created_at;struct tm tm;localtime_r(&v,&tm);strftime(t,sizeof(t),"%Y-%m-%d %H:%M:%S",&tm);printf("  %-24s %s\n",m.snaps[i].h.name,t);}free_meta(&m);}
static void cmd_rollback(const char *dir,const char *name){metadata_t m;load_meta(dir,&m);int i=find_snapshot(&m,name);if(i<0)fail("snapshot not found");memcpy(m.current,m.snaps[i].map,(size_t)m.h.logical_blocks*sizeof(uint64_t));m.h.generation++;save_meta(dir,&m);free_meta(&m);notify_driver(SNAPMON_ROLLBACK);printf("Rolled back to '%s'\n",name);}
static void cmd_delete(const char *dir,const char *name){metadata_t m;load_meta(dir,&m);int i=find_snapshot(&m,name);if(i<0)fail("snapshot not found");free(m.snaps[i].map);for(uint32_t j=(uint32_t)i;j+1<m.h.snapshot_count;j++)m.snaps[j]=m.snaps[j+1];m.h.snapshot_count--;m.h.generation++;save_meta(dir,&m);free_meta(&m);printf("Deleted snapshot '%s'\n",name);}
static void cmd_stats(const char *dir){metadata_t m;load_meta(dir,&m);char path[PATH_MAX];path_join(path,sizeof(path),dir,"blocks.dat");struct stat st;if(stat(path,&st)<0)die("stat blocks.dat");uint32_t mapped=0;for(uint32_t i=0;i<m.h.logical_blocks;i++)if(m.current[i]!=SNAPSTORE_UNMAPPED)mapped++;printf("Store: %s\nLogical blocks: %u\nMapped blocks: %u\nSnapshots: %u\nGeneration: %" PRIu64 "\nPhysical bytes: %" PRIu64 "\n",dir,m.h.logical_blocks,mapped,m.h.snapshot_count,m.h.generation,(uint64_t)st.st_size);free_meta(&m);}
static void cmd_verify(const char *dir){metadata_t m;load_meta(dir,&m);unsigned char buf[SNAPSTORE_BLOCK_SIZE];record_header_t h;uint64_t checked=0;for(uint32_t i=0;i<m.h.logical_blocks;i++)if(m.current[i]!=SNAPSTORE_UNMAPPED){if(read_record(dir,m.current[i],i,buf,&h)<0)fail("verification failed in current map");checked++;}for(uint32_t s=0;s<m.h.snapshot_count;s++)for(uint32_t i=0;i<m.h.logical_blocks;i++)if(m.snaps[s].map[i]!=SNAPSTORE_UNMAPPED){if(read_record(dir,m.snaps[s].map[i],i,buf,&h)<0)fail("verification failed in snapshot map");checked++;}printf("Verification OK: %" PRIu64 " mapped references checked\n",checked);free_meta(&m);}
static void usage(const char *p){fprintf(stderr,"Usage:\n  %s init STORE BLOCKS\n  %s write STORE BLOCK INPUT\n  %s read STORE BLOCK OUTPUT\n  %s snapshot STORE NAME\n  %s list STORE\n  %s rollback STORE NAME\n  %s delete-snapshot STORE NAME\n  %s stats STORE\n  %s verify STORE\n",p,p,p,p,p,p,p,p,p);exit(EXIT_FAILURE);}
int main(int c,char **v){if(c<2)usage(v[0]);if(!strcmp(v[1],"init")&&c==4)cmd_init(v[2],v[3]);else if(!strcmp(v[1],"write")&&c==5)cmd_write(v[2],v[3],v[4]);else if(!strcmp(v[1],"read")&&c==5)cmd_read(v[2],v[3],v[4]);else if(!strcmp(v[1],"snapshot")&&c==4)cmd_snapshot(v[2],v[3]);else if(!strcmp(v[1],"list")&&c==3)cmd_list(v[2]);else if(!strcmp(v[1],"rollback")&&c==4)cmd_rollback(v[2],v[3]);else if(!strcmp(v[1],"delete-snapshot")&&c==4)cmd_delete(v[2],v[3]);else if(!strcmp(v[1],"stats")&&c==3)cmd_stats(v[2]);else if(!strcmp(v[1],"verify")&&c==3)cmd_verify(v[2]);else usage(v[0]);return 0;}
